#
# docker-compose.yml
# This file is part of Vivarium.
#
# Copyright (C) 2019 Jeffery To
# https://github.com/jefferyto/openwrt-vivarium
#
# Vivarium is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Vivarium is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Vivarium.  If not, see <https://www.gnu.org/licenses/>.
#

version: "3"

services:
  builder:
    build:
      context: .
      dockerfile: builder/Dockerfile
      args:
        # Which SDK image to use
        # Available tags can be found at
        # https://hub.docker.com/r/openwrt/sdk/tags
        CONTAINER: openwrt/sdk
        TAG: ath79-generic-v22.03.4

    environment:
      # Clone package feeds from GitHub instead of git.openwrt.org (y or n)
      USE_GITHUB_FEEDS: y

      # Sets the corresponding config options (y or n)
      CONFIG_AUTOREMOVE: y
      CONFIG_BUILD_LOG: n

    volumes:
      # Where custom packages should be placed
      - "./packages:/vivarium/packages"

      # Contains build artifacts
      - "./sdk/bin:/builder/bin"
      - "./sdk/build_dir:/builder/build_dir"
      - "./sdk/dl:/builder/dl"
      - "./sdk/feeds:/builder/feeds"
      - "./sdk/logs:/builder/logs"
      - "./sdk/package/feeds:/builder/package/feeds"
      - "./sdk/staging_dir:/builder/staging_dir"
      - "./sdk/tmp:/builder/tmp"

      # Files in overrides will be copied into the sdk/build directory
      # directly; if there is a file named "diffconfig", it will be
      # copied to ".config", then expanded by "make defconfig"
      - "./sdk/overrides:/vivarium/overrides"
